/// Flutter icons LabIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  LabIcons
///      fonts:
///       - asset: fonts/LabIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class LabIcons {
  LabIcons._();

  static const _kFontFam = 'LabIcons';
  static const _kFontPkg = null;

  static const IconData tripod = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alcohol = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData atom = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beaker_1 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beaker = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData benzene_1 = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData biohazard = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData burner = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData benzene = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chemicals = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData burner_1 = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dropper = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dropper_1 = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flask = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chemicals_1 = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flask_4 = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flask_3 = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flask_2 = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flask_5 = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cube = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chemicals_2 = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cylinder = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData danger = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flask_9 = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dna = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData goggles = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flask_1 = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lab_coat = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flask_6 = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData loupe = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData magnetism = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData microscope = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData funnel = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData measuring_cup = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData molecule = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData molecule_1 = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData oil = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flask_8 = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData glass = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData petri_dish = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData radiation = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData test_tube = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thermometer = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData molecule_2 = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData funnel_1 = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData test_tube_1 = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData test_tube_2 = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData test_tube_3 = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flask_7 = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thermometer_1 = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
